linters:
  rubocop:
    display_cop_names: true
    fixer: true
files:
  ignore:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'test/test.helper.rb'
    - 'db/seeds.rb'
    - 'app/helpers/sessions_helper.rb'
    - 'config/*'
    - 'bin/*'
    - 'app/controllers/sessions_controller.rb'